SuperStrict

Import "src/*.h"
Import "src/common/*.h"
Import "src/liblzma/api/*.h"
Import "src/liblzma/common/*.h"
Import "src/liblzma/check/*.h"
Import "src/liblzma/delta/*.h"
Import "src/liblzma/lzma/*.h"
Import "src/liblzma/lz/*.h"
Import "src/liblzma/rangecoder/*.h"
Import "src/liblzma/simple/*.h"

Import "src/liblzma/check/check.c"
Import "src/liblzma/check/crc32_fast.c"
Import "src/liblzma/check/crc32_table.c"
Import "src/liblzma/check/crc32_tablegen.c"
Import "src/liblzma/check/crc64_fast.c"
Import "src/liblzma/check/crc64_table.c"
Import "src/liblzma/check/crc64_tablegen.c"
Import "src/liblzma/check/sha256.c"

Import "src/liblzma/common/alone_decoder.c"
Import "src/liblzma/common/alone_encoder.c"
Import "src/liblzma/common/auto_decoder.c"
Import "src/liblzma/common/block_buffer_decoder.c"
Import "src/liblzma/common/block_buffer_encoder.c"
Import "src/liblzma/common/block_decoder.c"
Import "src/liblzma/common/block_encoder.c"
Import "src/liblzma/common/block_header_decoder.c"
Import "src/liblzma/common/block_header_encoder.c"
Import "src/liblzma/common/block_util.c"
Import "src/liblzma/common/common.c"
Import "src/liblzma/common/easy_buffer_encoder.c"
Import "src/liblzma/common/easy_decoder_memusage.c"
Import "src/liblzma/common/easy_encoder_memusage.c"
Import "src/liblzma/common/easy_encoder.c"
Import "src/liblzma/common/easy_preset.c"
Import "src/liblzma/common/filter_buffer_decoder.c"
Import "src/liblzma/common/filter_buffer_encoder.c"
Import "src/liblzma/common/filter_common.c"
Import "src/liblzma/common/filter_decoder.c"
Import "src/liblzma/common/filter_encoder.c"
Import "src/liblzma/common/filter_flags_decoder.c"
Import "src/liblzma/common/filter_flags_encoder.c"
Import "src/liblzma/common/hardware_physmem.c"
Import "src/liblzma/common/index_decoder.c"
Import "src/liblzma/common/index_encoder.c"
Import "src/liblzma/common/index_hash.c"
Import "src/liblzma/common/index.c"
Import "src/liblzma/common/stream_buffer_decoder.c"
Import "src/liblzma/common/stream_buffer_encoder.c"
Import "src/liblzma/common/stream_decoder.c"
Import "src/liblzma/common/stream_encoder.c"
Import "src/liblzma/common/stream_flags_common.c"
Import "src/liblzma/common/stream_flags_decoder.c"
Import "src/liblzma/common/stream_flags_encoder.c"
Import "src/liblzma/common/vli_decoder.c"
Import "src/liblzma/common/vli_encoder.c"
Import "src/liblzma/common/vli_size.c"

Import "src/liblzma/delta/delta_common.c"
Import "src/liblzma/delta/delta_decoder.c"
Import "src/liblzma/delta/delta_encoder.c"

Import "src/liblzma/lz/lz_decoder.c"
Import "src/liblzma/lz/lz_encoder_mf.c"
Import "src/liblzma/lz/lz_encoder.c"

Import "src/liblzma/lzma/fastpos_table.c"
Import "src/liblzma/lzma/fastpos_tablegen.c"
Import "src/liblzma/lzma/lzma_decoder.c"
Import "src/liblzma/lzma/lzma_encoder_optimum_fast.c"
Import "src/liblzma/lzma/lzma_encoder_optimum_normal.c"
Import "src/liblzma/lzma/lzma_encoder_presets.c"
Import "src/liblzma/lzma/lzma_encoder.c"
Import "src/liblzma/lzma/lzma2_decoder.c"
Import "src/liblzma/lzma/lzma2_encoder.c"

Import "src/liblzma/rangecoder/price_table.c"
Import "src/liblzma/rangecoder/price_tablegen.c"

Import "src/liblzma/simple/simple_coder.c"
Import "src/liblzma/simple/simple_decoder.c"
Import "src/liblzma/simple/simple_encoder.c"
Import "src/liblzma/simple/x86.c"

