' Copyright (c) 2016-2019 Bruce A Henderson
' 
' Permission to use, copy, modify, and/or distribute this software for any purpose
' with or without fee is hereby granted, provided that the above copyright notice
' and this permission notice appear in all copies.
' 
' THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
' REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
' FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
' INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
' OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
' TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
' THIS SOFTWARE.
'
SuperStrict

Import "libsodium/src/libsodium/include/sodium/*.h"

Import "libsodium/src/libsodium/crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c"
Import "libsodium/src/libsodium/crypto_aead/chacha20poly1305/sodium/aead_chacha20poly1305.c"
Import "libsodium/src/libsodium/crypto_aead/xchacha20poly1305/sodium/aead_xchacha20poly1305.c"
Import "libsodium/src/libsodium/crypto_auth/crypto_auth.c"
Import "libsodium/src/libsodium/crypto_auth/hmacsha256/auth_hmacsha256.c"
Import "libsodium/src/libsodium/crypto_auth/hmacsha512/auth_hmacsha512.c"
Import "libsodium/src/libsodium/crypto_auth/hmacsha512256/auth_hmacsha512256.c"
Import "libsodium/src/libsodium/crypto_box/crypto_box.c"
Import "libsodium/src/libsodium/crypto_box/crypto_box_easy.c"
Import "libsodium/src/libsodium/crypto_box/crypto_box_seal.c"
Import "libsodium/src/libsodium/crypto_box/curve25519xchacha20poly1305/box_curve25519xchacha20poly1305.c"
Import "libsodium/src/libsodium/crypto_box/curve25519xchacha20poly1305/box_seal_curve25519xchacha20poly1305.c"
Import "libsodium/src/libsodium/crypto_box/curve25519xsalsa20poly1305/box_curve25519xsalsa20poly1305.c"
Import "libsodium/src/libsodium/crypto_core/ed25519/core_ed25519.c"
Import "libsodium/src/libsodium/crypto_core/ed25519/ref10/ed25519_ref10.c"
Import "libsodium/src/libsodium/crypto_core/hchacha20/core_hchacha20.c"
Import "libsodium/src/libsodium/crypto_core/hsalsa20/core_hsalsa20.c"
Import "libsodium/src/libsodium/crypto_core/hsalsa20/ref2/core_hsalsa20_ref2.c"
Import "libsodium/src/libsodium/crypto_core/salsa/ref/core_salsa_ref.c"
Import "libsodium/src/libsodium/crypto_generichash/blake2b/generichash_blake2.c"
Import "libsodium/src/libsodium/crypto_generichash/blake2b/ref/blake2b-compress-avx2.c"
Import "libsodium/src/libsodium/crypto_generichash/blake2b/ref/blake2b-compress-ref.c"
Import "libsodium/src/libsodium/crypto_generichash/blake2b/ref/blake2b-compress-sse41.c"
Import "libsodium/src/libsodium/crypto_generichash/blake2b/ref/blake2b-compress-ssse3.c"
Import "libsodium/src/libsodium/crypto_generichash/blake2b/ref/blake2b-ref.c"
Import "libsodium/src/libsodium/crypto_generichash/blake2b/ref/generichash_blake2b.c"
Import "libsodium/src/libsodium/crypto_generichash/crypto_generichash.c"
Import "libsodium/src/libsodium/crypto_hash/crypto_hash.c"
Import "libsodium/src/libsodium/crypto_hash/sha256/cp/hash_sha256_cp.c"
Import "libsodium/src/libsodium/crypto_hash/sha256/hash_sha256.c"
Import "libsodium/src/libsodium/crypto_hash/sha512/cp/hash_sha512_cp.c"
Import "libsodium/src/libsodium/crypto_hash/sha512/hash_sha512.c"
Import "libsodium/src/libsodium/crypto_kdf/blake2b/kdf_blake2b.c"
Import "libsodium/src/libsodium/crypto_kdf/crypto_kdf.c"
Import "libsodium/src/libsodium/crypto_kx/crypto_kx.c"
Import "libsodium/src/libsodium/crypto_onetimeauth/crypto_onetimeauth.c"
Import "libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna.c"
Import "libsodium/src/libsodium/crypto_onetimeauth/poly1305/onetimeauth_poly1305.c"
Import "libsodium/src/libsodium/crypto_onetimeauth/poly1305/sse2/poly1305_sse2.c"
Import "libsodium/src/libsodium/crypto_pwhash/argon2/argon2-core.c"
Import "libsodium/src/libsodium/crypto_pwhash/argon2/argon2-encoding.c"
Import "libsodium/src/libsodium/crypto_pwhash/argon2/argon2-fill-block-avx2.c"
Import "libsodium/src/libsodium/crypto_pwhash/argon2/argon2-fill-block-avx512f.c"
Import "libsodium/src/libsodium/crypto_pwhash/argon2/argon2-fill-block-ref.c"
Import "libsodium/src/libsodium/crypto_pwhash/argon2/argon2-fill-block-ssse3.c"
Import "libsodium/src/libsodium/crypto_pwhash/argon2/argon2.c"
Import "libsodium/src/libsodium/crypto_pwhash/argon2/blake2b-long.c"
Import "libsodium/src/libsodium/crypto_pwhash/argon2/pwhash_argon2i.c"
Import "libsodium/src/libsodium/crypto_pwhash/argon2/pwhash_argon2id.c"
Import "libsodium/src/libsodium/crypto_pwhash/crypto_pwhash.c"
Import "libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/crypto_scrypt-common.c"
Import "libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/nosse/pwhash_scryptsalsa208sha256_nosse.c"
Import "libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/pbkdf2-sha256.c"
Import "libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/pwhash_scryptsalsa208sha256.c"
Import "libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/scrypt_platform.c"
Import "libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/sse/pwhash_scryptsalsa208sha256_sse.c"
Import "libsodium/src/libsodium/crypto_scalarmult/crypto_scalarmult.c"
Import "libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c"
Import "libsodium/src/libsodium/crypto_scalarmult/curve25519/sandy2x/curve25519_sandy2x.c"
Import "libsodium/src/libsodium/crypto_scalarmult/curve25519/sandy2x/fe51_invert.c"
Import "libsodium/src/libsodium/crypto_scalarmult/curve25519/sandy2x/fe_frombytes_sandy2x.c"
Import "libsodium/src/libsodium/crypto_scalarmult/curve25519/scalarmult_curve25519.c"
Import "libsodium/src/libsodium/crypto_scalarmult/ed25519/ref10/scalarmult_ed25519_ref10.c"
Import "libsodium/src/libsodium/crypto_secretbox/crypto_secretbox.c"
Import "libsodium/src/libsodium/crypto_secretbox/crypto_secretbox_easy.c"
Import "libsodium/src/libsodium/crypto_secretbox/xchacha20poly1305/secretbox_xchacha20poly1305.c"
Import "libsodium/src/libsodium/crypto_secretbox/xsalsa20poly1305/secretbox_xsalsa20poly1305.c"
Import "libsodium/src/libsodium/crypto_secretstream/xchacha20poly1305/secretstream_xchacha20poly1305.c"
Import "libsodium/src/libsodium/crypto_shorthash/crypto_shorthash.c"
Import "libsodium/src/libsodium/crypto_shorthash/siphash24/ref/shorthash_siphash24_ref.c"
Import "libsodium/src/libsodium/crypto_shorthash/siphash24/ref/shorthash_siphashx24_ref.c"
Import "libsodium/src/libsodium/crypto_shorthash/siphash24/shorthash_siphash24.c"
Import "libsodium/src/libsodium/crypto_shorthash/siphash24/shorthash_siphashx24.c"
Import "libsodium/src/libsodium/crypto_sign/crypto_sign.c"
Import "libsodium/src/libsodium/crypto_sign/ed25519/ref10/keypair.c"
Import "libsodium/src/libsodium/crypto_sign/ed25519/ref10/obsolete.c"
Import "libsodium/src/libsodium/crypto_sign/ed25519/ref10/open.c"
Import "libsodium/src/libsodium/crypto_sign/ed25519/ref10/sign.c"
Import "libsodium/src/libsodium/crypto_sign/ed25519/sign_ed25519.c"
Import "libsodium/src/libsodium/crypto_stream/chacha20/dolbeau/chacha20_dolbeau-avx2.c"
Import "libsodium/src/libsodium/crypto_stream/chacha20/dolbeau/chacha20_dolbeau-ssse3.c"
Import "libsodium/src/libsodium/crypto_stream/chacha20/ref/chacha20_ref.c"
Import "libsodium/src/libsodium/crypto_stream/chacha20/stream_chacha20.c"
Import "libsodium/src/libsodium/crypto_stream/crypto_stream.c"
Import "libsodium/src/libsodium/crypto_stream/salsa20/ref/salsa20_ref.c"
Import "libsodium/src/libsodium/crypto_stream/salsa20/stream_salsa20.c"
Import "libsodium/src/libsodium/crypto_stream/salsa20/xmm6/salsa20_xmm6.c"
Import "libsodium/src/libsodium/crypto_stream/salsa20/xmm6int/salsa20_xmm6int-avx2.c"
Import "libsodium/src/libsodium/crypto_stream/salsa20/xmm6int/salsa20_xmm6int-sse2.c"
Import "libsodium/src/libsodium/crypto_stream/salsa2012/ref/stream_salsa2012_ref.c"
Import "libsodium/src/libsodium/crypto_stream/salsa2012/stream_salsa2012.c"
Import "libsodium/src/libsodium/crypto_stream/salsa208/ref/stream_salsa208_ref.c"
Import "libsodium/src/libsodium/crypto_stream/salsa208/stream_salsa208.c"
Import "libsodium/src/libsodium/crypto_stream/xchacha20/stream_xchacha20.c"
Import "libsodium/src/libsodium/crypto_stream/xsalsa20/stream_xsalsa20.c"
Import "libsodium/src/libsodium/crypto_verify/sodium/verify.c"
Import "libsodium/src/libsodium/randombytes/randombytes.c"
Import "libsodium/src/libsodium/randombytes/internal/randombytes_internal_random.c"
Import "libsodium/src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c"
Import "libsodium/src/libsodium/sodium/codecs.c"
Import "libsodium/src/libsodium/sodium/core.c"
Import "libsodium/src/libsodium/sodium/runtime.c"
Import "libsodium/src/libsodium/sodium/utils.c"
Import "libsodium/src/libsodium/sodium/version.c"


