SuperStrict

' libmodplug
Import "../soloud.mod/soloud/ext/libmodplug/src/libmodplug/*.h"
Import "../soloud.mod/soloud/ext/libmodplug/src/*.h"
Import "../soloud.mod/soloud/ext/libmodplug/src/fastmix.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_669.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_abc.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_amf.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_ams.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_dbm.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_dmf.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_dsm.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_far.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_it.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_j2b.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_mdl.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_med.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_mid.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_mod.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_mt2.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_mtm.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_okt.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_pat.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_psm.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_ptm.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_s3m.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_stm.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_ult.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_umx.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_wav.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/load_xm.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/mmcmp.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/modplug.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/snd_dsp.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/snd_flt.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/snd_fx.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/sndfile.cpp"
Import "../soloud.mod/soloud/ext/libmodplug/src/sndmix.cpp"


