/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */


/* Define to 1 if you have the <dlfcn.h> header file. */
#if defined(__APPLE__)
# define HAVE_DLFCN_H 1
#endif

/* Define to 1 if you have the `FcFini' function. */
/* #undef HAVE_FCFINI */

/* FT_Bitmap_Size structure includes y_ppem field */
/* #undef HAVE_FT_BITMAP_SIZE_Y_PPEM */

/* Define to 1 if you have the `FT_GlyphSlot_Embolden' function. */
/* #undef HAVE_FT_GLYPHSLOT_EMBOLDEN */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <pthread.h> header file. */
#if !defined(WIN32)
#define HAVE_PTHREAD_H 1
#else
#define CAIRO_NO_MUTEX 1
#define CAIRO_HAS_WIN32_SURFACE 1
#define CAIRO_WIN32_STATIC_BUILD 1
#endif

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/int_types.h> header file. */
/* #define HAVE_SYS_INT_TYPES_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if the system has the type `uint128_t'. */
/* #undef HAVE_UINT128_T */

/* Define to 1 if the system has the type `uint64_t'. */
#define HAVE_UINT64_T 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vasnprintf' function. */
/* #undef HAVE_VASNPRINTF */

/* Define to 1 if you have the `XrmFinalize' function. */
/* #undef HAVE_XRMFINALIZE */

/* Define to 1 if you have the <windows.h> header file. */
#ifdef WIN32
#define HAVE_WINDOWS_H 1
#endif


/* Name of package */
#define PACKAGE "cairo"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "http://bugs.freedesktop.org/enter_bug.cgi?product=cairo"

/* Define to the full name of this package. */
#define PACKAGE_NAME "cairo"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "cairo 1.4.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "cairo"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.4.2"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* use MMX compiler intrinsics */
/* #undef USE_MMX */

/* Version number of package */
#define VERSION "1.4.2"

/* Deal with multiple architecture compiles on Mac OS X */
#ifdef __APPLE_CC__
#ifdef __BIG_ENDIAN__
#define WORDS_BIGENDIAN 1
#define FLOAT_WORDS_BIGENDIAN 1
#else
#undef WORDS_BIGENDIAN
#undef FLOAT_WORDS_BIGENDIAN
#endif
#endif

/* Define to 1 if the X Window System is missing or not being used. */
#define X_DISPLAY_MISSING 1
