// Protocol Buffers - Google's data interchange format
// Copyright 2008 Google Inc.  All rights reserved.
// http://code.google.com/p/protobuf/
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Author: kenton@google.com (Kenton Varda)
//  Based on original Protocol Buffers design by
//  Sanjay Ghemawat, Jeff Dean, and others.

#include <bah/protobuf/compiler/blitzmax/bmx_file.h>
#include <bah/protobuf/compiler/blitzmax/bmx_enum.h>
#include <bah/protobuf/compiler/blitzmax/bmx_service.h>
#include <bah/protobuf/compiler/blitzmax/bmx_extension.h>
#include <bah/protobuf/compiler/blitzmax/bmx_helpers.h>
#include <bah/protobuf/compiler/blitzmax/bmx_message.h>
#include <google/protobuf/io/printer.h>
#include <google/protobuf/descriptor.pb.h>
#include <google/protobuf/stubs/strutil.h>

namespace google {
namespace protobuf {
namespace compiler {
namespace bmx {

// ===================================================================

FileGenerator::FileGenerator(const FileDescriptor* file,
                             const string& dllexport_decl)
  : file_(file),
    message_generators_(
      new scoped_ptr<MessageGenerator>[file->message_type_count()]),
    enum_generators_(
      new scoped_ptr<EnumGenerator>[file->enum_type_count()]),
    service_generators_(
      new scoped_ptr<ServiceGenerator>[file->service_count()]),
    extension_generators_(
      new scoped_ptr<ExtensionGenerator>[file->extension_count()]) {

  for (int i = 0; i < file->message_type_count(); i++) {
    message_generators_[i].reset(
      new MessageGenerator(file->message_type(i), dllexport_decl));
  }

  for (int i = 0; i < file->enum_type_count(); i++) {
    enum_generators_[i].reset(
      new EnumGenerator(file->enum_type(i), dllexport_decl));
  }

  for (int i = 0; i < file->service_count(); i++) {
    service_generators_[i].reset(
      new ServiceGenerator(file->service(i), dllexport_decl));
  }

  for (int i = 0; i < file->extension_count(); i++) {
    extension_generators_[i].reset(
      new ExtensionGenerator(file->extension(i), dllexport_decl));
  }

  SplitStringUsing(file_->package(), ".", &package_parts_);
}

FileGenerator::~FileGenerator() {}

void FileGenerator::GenerateGlue(io::Printer* printer) {

  string filename_identifier = FilenameIdentifier(file_->name());
  string basename = StripProto(file_->name());


  // Generate top of header.
  printer->Print(
    "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
    "\n"
    "\n");

  printer->Print(
	"#include \"$basename$.pb.h\"\n"
	"\n", "basename", basename);


  // Open namespace.
  GenerateNamespaceOpeners(printer);


  // Generate forward declarations.
  printer->Print("\n"
  "extern \"C\" {\n"
  "\n"
  "#include \"blitz.h\"\n"
  
  "\n");
  printer->Indent();
  
  printer->Print("BBString * bah_protobuf__pbConvertUTF8ToMax(const char * s, int length);\n");
  
  for (int i = 0; i < file_->message_type_count(); i++) {
    message_generators_[i]->GenerateDeclarations(printer);
  }
  
  printer->Outdent();
  printer->Print("\n"
  "}\n"
  "\n");




  // Generate enum definitions.
 //// for (int i = 0; i < file_->message_type_count(); i++) {
 ///   message_generators_[i]->GenerateEnumDefinitions(printer);
//}

  // Generate forward declarations of classes.
  for (int i = 0; i < file_->message_type_count(); i++) {
    message_generators_[i]->GenerateGlue(printer);
  }

//  // Generate class methods.
//  for (int i = 0; i < file_->message_type_count(); i++) {
//    if (i > 0) {
//      printer->Print(kThinSeparator);
//      printer->Print("\n");
//    }
//    message_generators_[i]->GenerateInlineMethods(printer);
//  }

  // Close up namespace.
  GenerateNamespaceClosers(printer);

}

void FileGenerator::GenerateBmx(io::Printer* printer) {

  string filename_identifier = FilenameIdentifier(file_->name());
  string basename = StripProto(file_->name());


	char * modpath = getenv("MODPATH");

  // Generate top of header.
  printer->Print(
    "' Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
    "\n"
    "SuperStrict\n"
    "\n"
    "Import BaH.Protobuf\n"
    "Import BRL.Blitz\n"
    "\n"
    "\n");

  printer->Print(
	"Import \"$modpath$/bah.mod/protobuf.mod/src/*.h\"\n"
	"Import \"*.h\"\n"
	"Import \"$basename$.pb_glue.cpp\"\n"
	"Import \"$basename$.pb.cc\"\n"   // FIXME : change to .cpp
	"\n", "basename", basename, "modpath", modpath);

  // Generate enum definitions.
  for (int i = 0; i < file_->message_type_count(); i++) {
    message_generators_[i]->GenerateEnumDefinitions(printer);
  }

  // Generate forward declarations of classes.
  for (int i = 0; i < file_->message_type_count(); i++) {
    message_generators_[i]->GenerateType(printer);
  }

//  // Generate class methods.
//  for (int i = 0; i < file_->message_type_count(); i++) {
//    if (i > 0) {
//      printer->Print(kThinSeparator);
//      printer->Print("\n");
//    }
//    message_generators_[i]->GenerateInlineMethods(printer);
//  }

  // Generate forward declarations of classes.
  printer->Print("Extern\n"
  "\n");
  printer->Indent();
  
  for (int i = 0; i < file_->message_type_count(); i++) {
    message_generators_[i]->GenerateExterns(printer);
  }
  
  printer->Outdent();
  printer->Print("\n"
  "End Extern\n");


}

void FileGenerator::GenerateNamespaceOpeners(io::Printer* printer) {
  if (package_parts_.size() > 0) printer->Print("\n");

  for (int i = 0; i < package_parts_.size(); i++) {
    printer->Print("namespace $part$ {\n",
                   "part", package_parts_[i]);
  }
}

void FileGenerator::GenerateNamespaceClosers(io::Printer* printer) {
  if (package_parts_.size() > 0) printer->Print("\n");

  for (int i = package_parts_.size() - 1; i >= 0; i--) {
    printer->Print("}  // namespace $part$\n",
                   "part", package_parts_[i]);
  }
}


}  // namespace cpp
}  // namespace compiler
}  // namespace protobuf
}  // namespace google
