WINBOOL GetDiskFreeSpaceExW(LPCSTR , PULARGE_INTEGER , PULARGE_INTEGER , PULARGE_INTEGER )!
WINBOOL GetVolumeInformationW(LPCSTR , LPSTR , DWORD , LPDWORD , LPDWORD , LPDWORD , LPSTR , DWORD )!
DWORD GetLogicalDrives()!
UINT SetErrorMode(UINT )!
HANDLE FindFirstVolumeW(LPSTR , DWORD )!
WINBOOL FindNextVolumeW(HANDLE , LPSTR , DWORD )!
WINBOOL GetVolumePathNamesForVolumeNameW(LPCSTR , LPCH , DWORD , PDWORD )!
WINBOOL FindVolumeClose(HANDLE)!
