' Copyright (c) 2009 Bruce A Henderson
' All rights reserved.
'
' Redistribution and use in source and binary forms, with or without
' modification, are permitted provided that the following conditions are met:
'     * Redistributions of source code must retain the above copyright
'       notice, this list of conditions and the following disclaimer.
'     * Redistributions in binary form must reproduce the above copyright
'       notice, this list of conditions and the following disclaimer in the
'       documentation and/or other materials provided with the distribution.
'     * Neither the name of Bruce A Henderson nor the
'       names of its contributors may be used to endorse or promote products
'       derived from this software without specific prior written permission.
'
' THIS SOFTWARE IS PROVIDED BY Bruce A Henderson ``AS IS'' AND ANY
' EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
' WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
' DISCLAIMED. IN NO EVENT SHALL Bruce A Henderson BE LIABLE FOR ANY
' DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
' (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
' LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
' ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
' (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
' SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
'
SuperStrict


Import BRL.Blitz
Import Pub.StdC

Import "../boost.mod/src/*.hpp"


Import "glue.cpp"


Extern

	Function bmx_boost_math_factorial:Double(i:Int)
	Function bmx_boost_math_uncheckedfactorial:Double(i:Int)
	Function bmx_boost_math_maxfactorial:Int()
	Function bmx_boost_math_doublefactorial:Double(i:Int)
	Function bmx_boost_math_risingfactorial:Double(x:Double, i:Int)
	Function bmx_boost_math_fallingfactorial:Double(x:Double, i:Int)
	Function bmx_boost_math_binomialcoefficient:Double(n:Int, k:Int)

	Function bmx_boost_math_cbrt:Double(x:Double)
	Function bmx_boost_math_hypot:Double(x:Double, y:Double)
	Function bmx_boost_math_log1p:Double(x:Double)
	Function bmx_boost_math_expm1:Double(x:Double)
	Function bmx_boost_math_sqrt1pm1:Double(x:Double)
	Function bmx_boost_math_powm1:Double(x:Double, y:Double)
	Function bmx_boost_math_zeta:Double(z:Double)

	Function bmx_boost_math_sphbessel:Double(v:Int, x:Double)
	Function bmx_boost_math_sphneumann:Double(v:Int, x:Double)

	Function bmx_boost_math_binomial_distribution_create:Byte Ptr(n:Int, p:Double)
	Function bmx_boost_math_binomial_distribution_successfraction:Double(handle:Byte Ptr)
	Function bmx_boost_math_binomial_distribution_trials:Int(handle:Byte Ptr)
	Function bmx_boost_math_binomial_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_binomial_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_binomial_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_binomial_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_binomial_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_binomial_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_binomial_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_binomial_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_binomial_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_binomial_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_binomial_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_binomial_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_binomial_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_binomial_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_binomial_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_binomial_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_binomial_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	Function bmx_boost_math_bernoulli_distribution_create:Byte Ptr(p:Double)
	Function bmx_boost_math_bernoulli_distribution_successfraction:Double(handle:Byte Ptr)
	Function bmx_boost_math_bernoulli_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_bernoulli_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_bernoulli_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_bernoulli_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_bernoulli_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_bernoulli_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_bernoulli_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_bernoulli_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_bernoulli_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_bernoulli_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_bernoulli_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_bernoulli_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_bernoulli_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_bernoulli_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_bernoulli_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_bernoulli_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_bernoulli_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	
	Function bmx_boost_math_beta_distribution_create:Byte Ptr(a:Double, b:Double)
	Function bmx_boost_math_beta_distribution_alpha:Double(handle:Byte Ptr)
	Function bmx_boost_math_beta_distribution_beta:Double(handle:Byte Ptr)
	Function bmx_boost_math_beta_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_beta_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_beta_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_beta_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_beta_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_beta_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_beta_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_beta_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_beta_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_beta_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_beta_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_beta_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_beta_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_beta_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_beta_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_beta_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_beta_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	
	Function bmx_boost_math_cauchy_distribution_create:Byte Ptr(location:Double, scale:Double)
	Function bmx_boost_math_cauchy_distribution_location:Double(handle:Byte Ptr)
	Function bmx_boost_math_cauchy_distribution_scale:Double(handle:Byte Ptr)
	Function bmx_boost_math_cauchy_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_cauchy_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_cauchy_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_cauchy_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_cauchy_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_cauchy_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_cauchy_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_cauchy_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_cauchy_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_cauchy_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_cauchy_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_cauchy_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_cauchy_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_cauchy_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_cauchy_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_cauchy_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_cauchy_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	
	Function bmx_boost_math_chi_squared_distribution_create:Byte Ptr(i:Double)
	Function bmx_boost_math_chi_squared_distribution_degreesoffreedom:Double(handle:Byte Ptr)
	Function bmx_boost_math_chi_squared_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_chi_squared_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_chi_squared_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_chi_squared_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_chi_squared_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_chi_squared_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_chi_squared_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_chi_squared_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_chi_squared_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_chi_squared_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_chi_squared_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_chi_squared_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_chi_squared_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_chi_squared_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_chi_squared_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_chi_squared_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_chi_squared_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	
	Function bmx_boost_math_exponential_distribution_create:Byte Ptr(lambda:Double)
	Function bmx_boost_math_exponential_distribution_lambda:Double(handle:Byte Ptr)
	Function bmx_boost_math_exponential_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_exponential_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_exponential_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_exponential_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_exponential_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_exponential_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_exponential_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_exponential_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_exponential_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_exponential_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_exponential_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_exponential_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_exponential_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_exponential_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_exponential_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_exponential_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_exponential_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	
	Function bmx_boost_math_extreme_value_distribution_create:Byte Ptr(location:Double, scale:Double)
	Function bmx_boost_math_extreme_value_distribution_location:Double(handle:Byte Ptr)
	Function bmx_boost_math_extreme_value_distribution_scale:Double(handle:Byte Ptr)
	Function bmx_boost_math_extreme_value_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_extreme_value_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_extreme_value_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_extreme_value_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_extreme_value_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_extreme_value_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_extreme_value_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_extreme_value_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_extreme_value_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_extreme_value_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_extreme_value_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_extreme_value_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_extreme_value_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_extreme_value_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_extreme_value_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_extreme_value_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_extreme_value_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	
	Function bmx_boost_math_normal_distribution_create:Byte Ptr(_mean:Double, sd:Double)
	Function bmx_boost_math_normal_distribution_location:Double(handle:Byte Ptr)
	Function bmx_boost_math_normal_distribution_scale:Double(handle:Byte Ptr)
	Function bmx_boost_math_normal_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_normal_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_normal_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_normal_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_normal_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_normal_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_normal_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_normal_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_normal_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_normal_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_normal_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_normal_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_normal_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_normal_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_normal_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_normal_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_normal_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	
	Function bmx_boost_math_pareto_distribution_create:Byte Ptr(location:Double, shape:Double)
	Function bmx_boost_math_pareto_distribution_location:Double(handle:Byte Ptr)
	Function bmx_boost_math_pareto_distribution_shape:Double(handle:Byte Ptr)
	Function bmx_boost_math_pareto_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_pareto_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_pareto_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_pareto_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_pareto_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_pareto_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_pareto_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_pareto_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_pareto_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_pareto_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_pareto_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_pareto_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_pareto_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_pareto_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_pareto_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_pareto_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_pareto_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	
	Function bmx_boost_math_weibull_distribution_create:Byte Ptr(shape:Double, scale:Double)
	Function bmx_boost_math_weibull_distribution_shape:Double(handle:Byte Ptr)
	Function bmx_boost_math_weibull_distribution_scale:Double(handle:Byte Ptr)
	Function bmx_boost_math_weibull_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_weibull_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_weibull_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_weibull_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_weibull_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_weibull_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_weibull_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_weibull_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_weibull_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_weibull_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_weibull_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_weibull_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_weibull_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_weibull_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_weibull_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_weibull_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_weibull_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	Function bmx_boost_math_fisher_f_distribution_create:Byte Ptr(i:Double, j:Double)
	Function bmx_boost_math_fisher_f_distribution_degreesoffreedom1:Double(handle:Byte Ptr)
	Function bmx_boost_math_fisher_f_distribution_degreesoffreedom2:Double(handle:Byte Ptr)
	Function bmx_boost_math_fisher_f_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_fisher_f_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_fisher_f_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_fisher_f_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_fisher_f_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_fisher_f_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_fisher_f_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_fisher_f_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_fisher_f_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_fisher_f_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_fisher_f_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_fisher_f_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_fisher_f_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_fisher_f_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_fisher_f_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_fisher_f_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_fisher_f_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	Function bmx_boost_math_lognormal_distribution_create:Byte Ptr(location:Double, scale:Double)
	Function bmx_boost_math_lognormal_distribution_location:Double(handle:Byte Ptr)
	Function bmx_boost_math_lognormal_distribution_scale:Double(handle:Byte Ptr)
	Function bmx_boost_math_lognormal_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_lognormal_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_lognormal_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_lognormal_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_lognormal_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_lognormal_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_lognormal_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_lognormal_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_lognormal_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_lognormal_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_lognormal_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_lognormal_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_lognormal_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_lognormal_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_lognormal_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_lognormal_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_lognormal_distribution_kurtosisexcess:Double(handle:Byte Ptr)


	Function bmx_boost_math_negative_binomial_distribution_create:Byte Ptr(r:Int, p:Double)
	Function bmx_boost_math_negative_binomial_distribution_successfraction:Double(handle:Byte Ptr)
	Function bmx_boost_math_negative_binomial_distribution_successes:Int(handle:Byte Ptr)
	Function bmx_boost_math_negative_binomial_distribution_findlowerboundonp:Double(trials:Int, successes:Int, probability:Double)
	Function bmx_boost_math_negative_binomial_distribution_findupperboundonp:Double(trials:Int, successes:Int, probability:Double)
	Function bmx_boost_math_negative_binomial_distribution_findminimumnumberoftrials:Double(k:Int, p:Double, probability:Double)
	Function bmx_boost_math_negative_binomial_distribution_findmaximumnumberoftrials:Double(k:Int, p:Double, probability:Double)
	Function bmx_boost_math_negative_binomial_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_negative_binomial_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_negative_binomial_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_negative_binomial_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_negative_binomial_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_negative_binomial_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_negative_binomial_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_negative_binomial_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_negative_binomial_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_negative_binomial_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_negative_binomial_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_negative_binomial_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_negative_binomial_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_negative_binomial_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_negative_binomial_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_negative_binomial_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_negative_binomial_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	Function bmx_boost_math_non_central_beta_distribution_create:Byte Ptr(alpha:Double, beta:Double, lambda:Double)
	Function bmx_boost_math_non_central_beta_distribution_alpha:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_beta_distribution_beta:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_beta_distribution_noncentrality:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_beta_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_beta_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_beta_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_beta_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_beta_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_beta_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_beta_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_non_central_beta_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_non_central_beta_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_beta_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_beta_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_non_central_beta_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_non_central_beta_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_beta_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_non_central_beta_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_beta_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_beta_distribution_kurtosisexcess:Double(handle:Byte Ptr)


	Function bmx_boost_math_non_central_chi_squared_distribution_create:Byte Ptr(v:Double, lambda:Double)
	Function bmx_boost_math_non_central_chi_squared_distribution_degreesoffreedom:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_chi_squared_distribution_noncentrality:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_chi_squared_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_chi_squared_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_chi_squared_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_chi_squared_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_chi_squared_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_chi_squared_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_chi_squared_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_non_central_chi_squared_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_non_central_chi_squared_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_chi_squared_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_chi_squared_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_non_central_chi_squared_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_non_central_chi_squared_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_chi_squared_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_non_central_chi_squared_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_chi_squared_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_chi_squared_distribution_kurtosisexcess:Double(handle:Byte Ptr)


	Function bmx_boost_math_non_central_f_distribution_create:Byte Ptr(v1:Double, v2:Double, lambda:Double)
	Function bmx_boost_math_non_central_f_distribution_degreesoffreedom1:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_f_distribution_degreesoffreedom2:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_f_distribution_noncentrality:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_f_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_f_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_f_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_f_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_f_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_f_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_f_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_non_central_f_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_non_central_f_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_f_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_f_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_non_central_f_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_non_central_f_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_f_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_non_central_f_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_f_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_f_distribution_kurtosisexcess:Double(handle:Byte Ptr)


	Function bmx_boost_math_non_central_t_distribution_create:Byte Ptr(v:Double, delta:Double)
	Function bmx_boost_math_non_central_t_distribution_degreesoffreedom:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_t_distribution_noncentrality:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_t_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_t_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_t_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_t_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_t_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_t_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_t_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_non_central_t_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_non_central_t_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_t_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_non_central_t_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_non_central_t_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_non_central_t_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_t_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_non_central_t_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_t_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_non_central_t_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	Function bmx_boost_math_poisson_distribution_create:Byte Ptr(_mean:Double)
	Function bmx_boost_math_poisson_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_poisson_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_poisson_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_poisson_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_poisson_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_poisson_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_poisson_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_poisson_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_poisson_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_poisson_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_poisson_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_poisson_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_poisson_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_poisson_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_poisson_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_poisson_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_poisson_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	Function bmx_boost_math_rayleigh_distribution_create:Byte Ptr(sigma:Double)
	Function bmx_boost_math_rayleigh_distribution_sigma:Double(handle:Byte Ptr)
	Function bmx_boost_math_rayleigh_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_rayleigh_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_rayleigh_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_rayleigh_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_rayleigh_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_rayleigh_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_rayleigh_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_rayleigh_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_rayleigh_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_rayleigh_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_rayleigh_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_rayleigh_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_rayleigh_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_rayleigh_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_rayleigh_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_rayleigh_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_rayleigh_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	Function bmx_boost_math_students_t_distribution_create:Byte Ptr(v:Double)
	Function bmx_boost_math_students_t_distribution_degreesoffreedom:Double(handle:Byte Ptr)
	Function bmx_boost_math_students_t_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_students_t_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_students_t_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_students_t_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_students_t_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_students_t_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_students_t_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_students_t_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_students_t_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_students_t_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_students_t_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_students_t_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_students_t_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_students_t_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_students_t_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_students_t_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_students_t_distribution_kurtosisexcess:Double(handle:Byte Ptr)

	Function bmx_boost_math_triangular_distribution_create:Byte Ptr(_lower:Double, _mode:Double, _upper:Double)
	Function bmx_boost_math_triangular_distribution_lower:Double(handle:Byte Ptr)
	Function bmx_boost_math_triangular_distribution_upper:Double(handle:Byte Ptr)
	Function bmx_boost_math_triangular_distribution_mean:Double(handle:Byte Ptr)
	Function bmx_boost_math_triangular_distribution_mode:Double(handle:Byte Ptr)
	Function bmx_boost_math_triangular_distribution_standarddeviation:Double(handle:Byte Ptr)
	Function bmx_boost_math_triangular_distribution_skewness:Double(handle:Byte Ptr)
	Function bmx_boost_math_triangular_distribution_pdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_triangular_distribution_cdf:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_triangular_distribution_free(handle:Byte Ptr)
	Function bmx_boost_math_triangular_distribution_quantile:Double(handle:Byte Ptr, p:Double)
	Function bmx_boost_math_triangular_distribution_cdfcomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_triangular_distribution_quantilecomplement:Double(handle:Byte Ptr, k:Double)
	Function bmx_boost_math_triangular_distribution_hazard:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_triangular_distribution_chf:Double(handle:Byte Ptr, x:Double)
	Function bmx_boost_math_triangular_distribution_median:Double(handle:Byte Ptr)
	Function bmx_boost_math_triangular_distribution_range(handle:Byte Ptr, rangeStart:Double Ptr, rangeEnd:Double Ptr)
	Function bmx_boost_math_triangular_distribution_variance:Double(handle:Byte Ptr)
	Function bmx_boost_math_triangular_distribution_kurtosis:Double(handle:Byte Ptr)
	Function bmx_boost_math_triangular_distribution_kurtosisexcess:Double(handle:Byte Ptr)

End Extern


Type TOverflowException Extends TRuntimeException
	
	Method CreateException:TOverflowException()
		Return Self
	End Method

	Function _create:TOverflowException()
		Return New TOverflowException.CreateException()
	End Function
	
	Method ToString:String()
		Return "Overflow Exception"
	End Method
	
End Type

Type TDomainException Extends TRuntimeException
	
	Method CreateException:TDomainException()
		Return Self
	End Method

	Function _create:TDomainException()
		Return New TDomainException.CreateException()
	End Function
	
	Method ToString:String()
		Return "Domain Exception"
	End Method
	
End Type
