' Copyright (c) 2007-2019 Bruce A Henderson
' 
' Permission is hereby granted, free of charge, to any person obtaining a copy
' of this software and associated documentation files (the "Software"), to deal
' in the Software without restriction, including without limitation the rights
' to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
' copies of the Software, and to permit persons to whom the Software is
' furnished to do so, subject to the following conditions:
' 
' The above copyright notice and this permission notice shall be included in
' all copies or substantial portions of the Software.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
' IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
' FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
' AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
' LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
' OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
' THE SOFTWARE.
'
SuperStrict

Import "src/*.h"
Import "src/FreeImage/*.h"
Import "src/LibWebP/*.h"

Import "src/FreeImage/PluginWebP.cpp"

Import "src/LibWebP/src/dec/alpha_dec.c"
Import "src/LibWebP/src/dec/buffer_dec.c"
Import "src/LibWebP/src/dec/frame_dec.c"
Import "src/LibWebP/src/dec/idec_dec.c"
Import "src/LibWebP/src/dec/io_dec.c"
Import "src/LibWebP/src/dec/quant_dec.c"
Import "src/LibWebP/src/dec/tree_dec.c"
Import "src/LibWebP/src/dec/vp8l_dec.c"
Import "src/LibWebP/src/dec/vp8_dec.c"
Import "src/LibWebP/src/dec/webp_dec.c"
Import "src/LibWebP/src/demux/anim_decode.c"
Import "src/LibWebP/src/demux/demux.c"
Import "src/LibWebP/src/dsp/alpha_processing.c"
Import "src/LibWebP/src/dsp/alpha_processing_mips_dsp_r2.c"
Import "src/LibWebP/src/dsp/alpha_processing_neon.c"
Import "src/LibWebP/src/dsp/alpha_processing_sse2.c"
Import "src/LibWebP/src/dsp/alpha_processing_sse41.c"
Import "src/LibWebP/src/dsp/cost.c"
Import "src/LibWebP/src/dsp/cost_mips32.c"
Import "src/LibWebP/src/dsp/cost_mips_dsp_r2.c"
Import "src/LibWebP/src/dsp/cost_sse2.c"
Import "src/LibWebP/src/dsp/cpu.c"
Import "src/LibWebP/src/dsp/dec.c"
Import "src/LibWebP/src/dsp/dec_clip_tables.c"
Import "src/LibWebP/src/dsp/dec_mips32.c"
Import "src/LibWebP/src/dsp/dec_mips_dsp_r2.c"
Import "src/LibWebP/src/dsp/dec_msa.c"
Import "src/LibWebP/src/dsp/dec_neon.c"
Import "src/LibWebP/src/dsp/dec_sse2.c"
Import "src/LibWebP/src/dsp/dec_sse41.c"
Import "src/LibWebP/src/dsp/enc.c"
Import "src/LibWebP/src/dsp/enc_avx2.c"
Import "src/LibWebP/src/dsp/enc_mips32.c"
Import "src/LibWebP/src/dsp/enc_mips_dsp_r2.c"
Import "src/LibWebP/src/dsp/enc_msa.c"
Import "src/LibWebP/src/dsp/enc_neon.c"
Import "src/LibWebP/src/dsp/enc_sse2.c"
Import "src/LibWebP/src/dsp/enc_sse41.c"
Import "src/LibWebP/src/dsp/filters.c"
Import "src/LibWebP/src/dsp/filters_mips_dsp_r2.c"
Import "src/LibWebP/src/dsp/filters_msa.c"
Import "src/LibWebP/src/dsp/filters_neon.c"
Import "src/LibWebP/src/dsp/filters_sse2.c"
Import "src/LibWebP/src/dsp/lossless.c"
Import "src/LibWebP/src/dsp/lossless_enc.c"
Import "src/LibWebP/src/dsp/lossless_enc_mips32.c"
Import "src/LibWebP/src/dsp/lossless_enc_mips_dsp_r2.c"
Import "src/LibWebP/src/dsp/lossless_enc_msa.c"
Import "src/LibWebP/src/dsp/lossless_enc_neon.c"
Import "src/LibWebP/src/dsp/lossless_enc_sse2.c"
Import "src/LibWebP/src/dsp/lossless_enc_sse41.c"
Import "src/LibWebP/src/dsp/lossless_mips_dsp_r2.c"
Import "src/LibWebP/src/dsp/lossless_msa.c"
Import "src/LibWebP/src/dsp/lossless_neon.c"
Import "src/LibWebP/src/dsp/lossless_sse2.c"
Import "src/LibWebP/src/dsp/rescaler.c"
Import "src/LibWebP/src/dsp/rescaler_mips32.c"
Import "src/LibWebP/src/dsp/rescaler_mips_dsp_r2.c"
Import "src/LibWebP/src/dsp/rescaler_msa.c"
Import "src/LibWebP/src/dsp/rescaler_neon.c"
Import "src/LibWebP/src/dsp/rescaler_sse2.c"
Import "src/LibWebP/src/dsp/ssim.c"
Import "src/LibWebP/src/dsp/ssim_sse2.c"
Import "src/LibWebP/src/dsp/upsampling.c"
Import "src/LibWebP/src/dsp/upsampling_msa.c"
Import "src/LibWebP/src/dsp/upsampling_neon.c"
Import "src/LibWebP/src/dsp/upsampling_sse2.c"
Import "src/LibWebP/src/dsp/upsampling_sse41.c"
Import "src/LibWebP/src/dsp/yuv.c"
Import "src/LibWebP/src/dsp/yuv_mips32.c"
Import "src/LibWebP/src/dsp/yuv_neon.c"
Import "src/LibWebP/src/dsp/yuv_sse2.c"
Import "src/LibWebP/src/dsp/yuv_sse41.c"
Import "src/LibWebP/src/enc/alpha_enc.c"
Import "src/LibWebP/src/enc/analysis_enc.c"
Import "src/LibWebP/src/enc/backward_references_cost_enc.c"
Import "src/LibWebP/src/enc/backward_references_enc.c"
Import "src/LibWebP/src/enc/config_enc.c"
Import "src/LibWebP/src/enc/cost_enc.c"
Import "src/LibWebP/src/enc/filter_enc.c"
Import "src/LibWebP/src/enc/frame_enc.c"
Import "src/LibWebP/src/enc/histogram_enc.c"
Import "src/LibWebP/src/enc/iterator_enc.c"
Import "src/LibWebP/src/enc/near_lossless_enc.c"
Import "src/LibWebP/src/enc/picture_csp_enc.c"
Import "src/LibWebP/src/enc/picture_enc.c"
Import "src/LibWebP/src/enc/picture_psnr_enc.c"
Import "src/LibWebP/src/enc/picture_rescale_enc.c"
Import "src/LibWebP/src/enc/picture_tools_enc.c"
Import "src/LibWebP/src/enc/predictor_enc.c"
Import "src/LibWebP/src/enc/quant_enc.c"
Import "src/LibWebP/src/enc/syntax_enc.c"
Import "src/LibWebP/src/enc/token_enc.c"
Import "src/LibWebP/src/enc/tree_enc.c"
Import "src/LibWebP/src/enc/vp8l_enc.c"
Import "src/LibWebP/src/enc/webp_enc.c"
Import "src/LibWebP/src/mux/anim_encode.c"
Import "src/LibWebP/src/mux/muxedit.c"
Import "src/LibWebP/src/mux/muxinternal.c"
Import "src/LibWebP/src/mux/muxread.c"
Import "src/LibWebP/src/utils/bit_reader_utils.c"
Import "src/LibWebP/src/utils/bit_writer_utils.c"
Import "src/LibWebP/src/utils/color_cache_utils.c"
Import "src/LibWebP/src/utils/filters_utils.c"
Import "src/LibWebP/src/utils/huffman_encode_utils.c"
Import "src/LibWebP/src/utils/huffman_utils.c"
Import "src/LibWebP/src/utils/quant_levels_dec_utils.c"
Import "src/LibWebP/src/utils/quant_levels_utils.c"
Import "src/LibWebP/src/utils/random_utils.c"
Import "src/LibWebP/src/utils/rescaler_utils.c"
Import "src/LibWebP/src/utils/thread_utils.c"
Import "src/LibWebP/src/utils/utils.c"



