/* xbase64/xbconfig.h.  Generated by configure.  */
/* xbase64/xbconfig.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `fseeko' function. */
#define HAVE_FSEEKO 1

/* Define to 1 if you have the `ftello' function. */
#define HAVE_FTELLO 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define to 1 if you have the `vsprintf' function. */
#define HAVE_VSPRINTF 1

/* Name of package */
#define PACKAGE "xbase64"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "xbase64-devel@lists.sourceforge.net"

/* Define to the full name of this package. */
#define PACKAGE_NAME "xbase64"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "xbase64 3.1.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "xbase64"

/* Define to the version of this package. */
#define PACKAGE_VERSION "3.1.2"

#define PATH_SEPARATOR '/'

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "3.1.2"

/* XB_DEBUG */
#define XBASE_DEBUG 1

#define XB_DBT_BLOCK_SIZE 512

/* XB_EXPRESSIONS */
#define XB_EXPRESSIONS 1

/* XB_FILTERS */
#define XB_FILTERS 1

/* XB_INDEX_ANY */
#define XB_INDEX_ANY 1

/* XB_INDEX_NDX */
#define XB_INDEX_NDX 1

/* XB_INDEX_NTX */
#define XB_INDEX_NTX 1

/* XB_LARGEFILE_SUPPORT */
#define XB_LARGEFILE_SUPPORT 1

/* XB_LOCKING_ON */
#define XB_LOCKING_ON 1

/* XB_MEMO_FIELDS */
#define XB_MEMO_FIELDS 1

/* XB_REAL_DELETE */
#define XB_REAL_DELETE 1

/* Define to 1 if on AIX 3.
   System headers sometimes define this.
   We just want to avoid a redefinition error message.  */
#ifndef _ALL_SOURCE
/* # undef _ALL_SOURCE */
#endif

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */

/* Define to 1 if on MINIX. */
/* #undef _MINIX */

/* Define to 2 if the system does not provide POSIX.1 features except with
   this defined. */
/* #undef _POSIX_1_SOURCE */

/* Define to 1 if you need to in order for `stat' and other things to work. */
/* #undef _POSIX_SOURCE */
